//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPTestStub) DeepCopyInto(out *HTTPTestStub) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPTestStub.
func (in *HTTPTestStub) DeepCopy() *HTTPTestStub {
	if in == nil {
		return nil
	}
	out := new(HTTPTestStub)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HTTPTestStub) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPTestStubList) DeepCopyInto(out *HTTPTestStubList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HTTPTestStub, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPTestStubList.
func (in *HTTPTestStubList) DeepCopy() *HTTPTestStubList {
	if in == nil {
		return nil
	}
	out := new(HTTPTestStubList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HTTPTestStubList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPTestStubSpec) DeepCopyInto(out *HTTPTestStubSpec) {
	*out = *in
	in.Request.DeepCopyInto(&out.Request)
	in.Response.DeepCopyInto(&out.Response)
	if in.Scripts != nil {
		in, out := &in.Scripts, &out.Scripts
		*out = make([]Script, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.TLS = in.TLS
	if in.Stubs != nil {
		in, out := &in.Stubs, &out.Stubs
		*out = make([]Stub, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPTestStubStatus) DeepCopyInto(out *HTTPTestStubStatus) {
	*out = *in
	if in.LastRequestTime != nil {
		in, out := &in.LastRequestTime, &out.LastRequestTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Request) DeepCopyInto(out *Request) {
	*out = *in
	out.URL = in.URL
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Response) DeepCopyInto(out *Response) {
	*out = *in
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = new(Static)
		(*in).DeepCopyInto(*out)
	}
	if in.Script != nil {
		in, out := &in.Script, &out.Script
		*out = new(Script)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Static) DeepCopyInto(out *Static) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Script) DeepCopyInto(out *Script) {
	*out = *in
	if in.Input != nil {
		in, out := &in.Input, &out.Input
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Stub) DeepCopyInto(out *Stub) {
	*out = *in
	in.Request.DeepCopyInto(&out.Request)
	if in.ResponseRules != nil {
		in, out := &in.ResponseRules, &out.ResponseRules
		*out = make([]ResponseRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Counter = in.Counter
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResponseRule) DeepCopyInto(out *ResponseRule) {
	*out = *in
	out.Rule = in.Rule
	if in.Response != nil {
		in, out := &in.Response, &out.Response
		*out = new(Static)
		(*in).DeepCopyInto(*out)
	}
}
