//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *HTTPTestStubSpec) DeepCopy() *HTTPTestStubSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPTestStubSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *HTTPTestStubSpec) DeepCopyInto(out *HTTPTestStubSpec) {
	*out = *in
	out.Protocol = in.Protocol
	out.Request = in.Request
	out.Response = in.Response
	if in.Scripts != nil {
		in, out := &in.Scripts, &out.Scripts
		*out = make([]Script, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.TLS = in.TLS
	if in.Stubs != nil {
		in, out := &in.Stubs, &out.Stubs
		*out = make([]Stub, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *HTTPTestStub) DeepCopyInto(out *HTTPTestStub) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

func (in *HTTPTestStub) DeepCopy() *HTTPTestStub {
	if in == nil {
		return nil
	}
	out := new(HTTPTestStub)
	in.DeepCopyInto(out)
	return out
}

func (in *HTTPTestStub) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HTTPTestStubList) DeepCopyInto(out *HTTPTestStubList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HTTPTestStub, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *HTTPTestStubList) DeepCopy() *HTTPTestStubList {
	if in == nil {
		return nil
	}
	out := new(HTTPTestStubList)
	in.DeepCopyInto(out)
	return out
}

func (in *HTTPTestStubList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *Request) DeepCopy() *Request {
	if in == nil {
		return nil
	}
	out := new(Request)
	*out = *in
	return out
}

func (in *Request) DeepCopyInto(out *Request) {
	*out = *in
	out.URL = in.URL
}

func (in *URL) DeepCopy() *URL {
	if in == nil {
		return nil
	}
	out := new(URL)
	*out = *in
	return out
}

func (in *URL) DeepCopyInto(out *URL) {
	*out = *in
}

func (in *Response) DeepCopy() *Response {
	if in == nil {
		return nil
	}
	out := new(Response)
	in.DeepCopyInto(out)
	return out
}

func (in *Response) DeepCopyInto(out *Response) {
	*out = *in
	out.Type = in.Type
	if in.Static != nil {
		out.Static = new(Static)
		in.Static.DeepCopyInto(out.Static)
	}
	if in.Script != nil {
		out.Script = new(Script)
		in.Script.DeepCopyInto(out.Script)
	}
}

func (in *Static) DeepCopy() *Static {
	if in == nil {
		return nil
	}
	out := new(Static)
	in.DeepCopyInto(out)
	return out
}

func (in *Static) DeepCopyInto(out *Static) {
	*out = *in
	out.Status = in.Status
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.Body = in.Body
}

func (in *Script) DeepCopy() *Script {
	if in == nil {
		return nil
	}
	out := new(Script)
	in.DeepCopyInto(out)
	return out
}

func (in *Script) DeepCopyInto(out *Script) {
	*out = *in
	out.Name = in.Name
	out.Type = in.Type
	out.Path = in.Path
	out.Timeout = in.Timeout
	if in.Input != nil {
		in, out := &in.Input, &out.Input
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Content = in.Content
}

func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	*out = *in
	return out
}

func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
}

func (in *Stub) DeepCopy() *Stub {
	if in == nil {
		return nil
	}
	out := new(Stub)
	in.DeepCopyInto(out)
	return out
}

func (in *Stub) DeepCopyInto(out *Stub) {
	*out = *in
	out.Request = in.Request
	if in.ResponseRules != nil {
		in, out := &in.ResponseRules, &out.ResponseRules
		*out = make([]ResponseRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Counter = in.Counter
}

func (in *ResponseRule) DeepCopy() *ResponseRule {
	if in == nil {
		return nil
	}
	out := new(ResponseRule)
	in.DeepCopyInto(out)
	return out
}

func (in *ResponseRule) DeepCopyInto(out *ResponseRule) {
	*out = *in
	out.Rule = in.Rule
	if in.Response != nil {
		out.Response = new(Static)
		in.Response.DeepCopyInto(out.Response)
	}
}

func (in *Rule) DeepCopy() *Rule {
	if in == nil {
		return nil
	}
	out := new(Rule)
	*out = *in
	return out
}

func (in *Rule) DeepCopyInto(out *Rule) {
	*out = *in
}

func (in *Counter) DeepCopy() *Counter {
	if in == nil {
		return nil
	}
	out := new(Counter)
	*out = *in
	return out
}

func (in *Counter) DeepCopyInto(out *Counter) {
	*out = *in
}

func (in *HTTPTestStubStatus) DeepCopy() *HTTPTestStubStatus {
	if in == nil {
		return nil
	}
	out := new(HTTPTestStubStatus)
	*out = *in
	return out
}

func (in *HTTPTestStubStatus) DeepCopyInto(out *HTTPTestStubStatus) {
	*out = *in
}
