apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-http-fake-operator.fullname" . }}
  labels:
    {{- include "k8s-http-fake-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ .Values.service.healthPort }}
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "k8s-http-fake-operator.selectorLabels" . | nindent 4 }}