apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-http-fake-operator.fullname" . }}
  labels:
    {{- include "k8s-http-fake-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - port: {{ include "k8s-http-fake-operator.defaultHTTPPort" . }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ include "k8s-http-fake-operator.defaultHTTPSPort" . }}
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ include "k8s-http-fake-operator.defaultHealthPort" . }}
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "k8s-http-fake-operator.selectorLabels" . | nindent 4 }}