{{- if and .Values.tls.enabled .Values.tls.autoGenerate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-http-fake-operator.defaultTLSCertSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "k8s-http-fake-operator.name" . }}
    helm.sh/chart: {{ include "k8s-http-fake-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: kubernetes.io/tls
data:
  tls.crt: {{ include "k8s-http-fake-operator.genCert" . | b64enc }}
  tls.key: {{ include "k8s-http-fake-operator.genKey" . | b64enc }}
{{- end }}
